name: 'Setup Lix'
description: 'Setup Lix (a package manager for Haxe)'
inputs:
  lix-version: 
    description: 'Version of Lix to use'
    required: true
    default: '15.8.9'
runs:
  using: 'node12'
  main: 'build/index.js'
